# Settings.yml

---
conf.py:
  copyright: 2000-2013
  project: Official Template
  version: 2.0.0
  release: 2.0.0
  html_theme_options:
    github_repository: TYPO3-Documentation/TYPO3CMS-Guide-Extbase
    github_branch: latest
...
